### ISSUE TITLE
Find a way to simply specify local actions

### ISSUE THREAD

**Issue by eshwen** [eshwen/adrenaline#13]
When a reusable workflow uses local actions in the repo, but the workflow is called from a separate repo, the actions can't be located.

This thread explains things: https://stackoverflow.com/a/73238189

For example:

```
eshwen/adrenaline
├─ .github/
│  ├─ workflows/
│  │  ├─ python-quality-check.yml

├─ check-python/
│  ├─ action.yml
```

And `python-quality-check.yml` contained

```yaml
...

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check code quality
        if: always()
        uses: ./check-python

...
```

If I ran the `python-quality-check.yml` from within the `adrenaline` repo itself, it would find the `check-python` action because the previous `actions/checkout` step would clone it.

However, this configuration won't work if I called `python-quality-check.yml` from another repo, since I would have to specifically clone a copy of `adrenaline` and make sure the paths are correct. But there's additional complexity because a GitHub Access Token has to be passed through to allow access to the repo (despite it being public)

It just adds too much complexity, so the simplest answer is to treat these local actions as if they are external to `adrenaline`. It adds some nuance, however, because if I don't actively maintain the versions of the actions and workflows properly, the workflow could call an outdated version of the action and not work correctly, unbeknownst to the user

Ideally, I want to fix this so that any reusable workflow in this repo that's called externally will always use the equivalent version of the action local to this repo
